#!/usr/bin/env python3
import listavulnerabilidades
import parser
import param
import progressbar
import report

args = param.arguments()

html_doc = open(args.file,'r')
htmlParser = parser.HtmlParser(html_doc)
htmlParser.mostrarTitulo()

vulnerabilidades = listavulnerabilidades.ListaVulnerabilidades()


print('[+] Loading report...')
vulnerabilidadesParseadas = htmlParser.getAllVuln()

print('[+] Translate in progress...')
progressBar = progressbar.ProgressBar(len(vulnerabilidadesParseadas))
progressBar.mostrar()
for vulnerabilidad in vulnerabilidadesParseadas:
    vulnerabilidad.traducir(args.language)
    vulnerabilidades.agregar(vulnerabilidad,excluir=['None','Info'])
    progressBar.siguiente()
    if(args.verbose):
        vulnerabilidad.mostrar()

if(args.excel):
    report.Report.toExcel(vulnerabilidades, args.excel, args.language)

if(args.word):
    report.Report.toWord(vulnerabilidades, args.word, args.language)


print('[+] Report complete')
