#!/usr/bin/env python3
from listavulnerabilidades import ListaVulnerabilidades
import parser
import param
import verbose
from progressbar import ProgressBar
from report import Report

def main():
    args = param.arguments()

    csvParser = parser.CsvParser(args.file)

    vulnerabilidades = ListaVulnerabilidades()

    print('[+] Loading report...')
    vulnerabilidadesParseadas = csvParser.getAllVuln()
    print('')
    print('[+] ' + str(len(vulnerabilidadesParseadas)) + ' vulnerabilities.')
    print('')

    print('[+] Translate in progress...')
    progressBar = ProgressBar(len(vulnerabilidadesParseadas))
    progressBar.mostrar()

    for vulnerabilidad in vulnerabilidadesParseadas:
        vulnerabilidad.traducir(args.language)
        vulnerabilidades.agregar(vulnerabilidad,excluir=['None','Info'])
        progressBar.siguiente()
        if args.verbose:
            vulnerabilidad.mostrar()

    print('')
    if(args.excel):
            Report.toExcel(vulnerabilidades, args.output, args.language)
            print('[+] Excel done')

    if(args.word):
        Report.toWord(vulnerabilidades, args.output, args.language, args.client, args.nmap)
        print('[+] Word done')

    print('')
    print('[+] Reports complete')

main()
